<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-02T06:17:30Z" name="Suite" finished-at="2019-06-02T06:17:33Z" duration-ms="2713">
    <groups>
    </groups>
    <test started-at="2019-06-02T06:17:30Z" name="Test1" finished-at="2019-06-02T06:17:33Z" duration-ms="2289">
      <class name="pack1.Telephony1">
        <test-method signature="ConnectTelephonyTest()[pri:0, instance:pack1.Telephony1@bccb269]" started-at="2019-06-02T06:17:31Z" name="ConnectTelephonyTest" finished-at="2019-06-02T06:17:32Z" duration-ms="1468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConnectTelephonyTest -->
        <test-method is-config="true" signature="flush()[pri:0, instance:pack1.Telephony1@bccb269]" started-at="2019-06-02T06:17:32Z" name="flush" finished-at="2019-06-02T06:17:32Z" duration-ms="208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush -->
        <test-method signature="DialTelephonyTest()[pri:0, instance:pack1.Telephony1@bccb269]" started-at="2019-06-02T06:17:32Z" name="DialTelephonyTest" finished-at="2019-06-02T06:17:32Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DialTelephonyTest -->
        <test-method is-config="true" signature="flush()[pri:0, instance:pack1.Telephony1@bccb269]" started-at="2019-06-02T06:17:32Z" name="flush" finished-at="2019-06-02T06:17:33Z" duration-ms="263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush -->
      </class> <!-- pack1.Telephony1 -->
    </test> <!-- Test1 -->
    <test started-at="2019-06-02T06:17:33Z" name="Test2" finished-at="2019-06-02T06:17:33Z" duration-ms="196">
      <class name="pack1.Telephony2">
        <test-method signature="DisConnectTelephonyTest()[pri:0, instance:pack1.Telephony2@38102d01]" started-at="2019-06-02T06:17:33Z" name="DisConnectTelephonyTest" finished-at="2019-06-02T06:17:33Z" duration-ms="184" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [hello world] but found [Zeenews]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [hello world] but found [Zeenews]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pack1.Telephony2.DisConnectTelephonyTest(Telephony2.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DisConnectTelephonyTest -->
      </class> <!-- pack1.Telephony2 -->
    </test> <!-- Test2 -->
    <test started-at="2019-06-02T06:17:33Z" name="Test3" finished-at="2019-06-02T06:17:33Z" duration-ms="145">
      <class name="pack1.Telephony3">
        <test-method signature="TransferTelephonyTest()[pri:0, instance:pack1.Telephony3@38e79ae3]" started-at="2019-06-02T06:17:33Z" name="TransferTelephonyTest" finished-at="2019-06-02T06:17:33Z" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TransferTelephonyTest -->
      </class> <!-- pack1.Telephony3 -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
